# Generated by Django 4.0.1 on 2022-01-24 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_movie_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.ImageField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1, upload_to=''),
        ),
    ]
