# Generated by Django 4.0.1 on 2022-01-25 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_movie_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='family_name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
